=== marisademeglio/audiobooks-js/example/schema/publication.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "publication.schema.json",
	"title": "Publication Manifest",
	"type": "object",
	"properties": {
		"@context": {
			"$ref": "context.schema.json"
		},
		"type": {
			"type": [
				"string",
				"array"
			],
			"items": {
				"type": "string"
			},
			"uniqueItems": true
		},
		"conformsTo" : {
			"oneOf": [
				{
					"$ref": "url.schema.json"
				},
				{
					"type": "array",
					"items": {
						"$ref": "url.schema.json"
					}		
				}
			]
		},
		"id": {
			"type": "string"
		},
		"abridged": {
			"type": "boolean"
		},
		"accessMode": {
			"$ref": "strings.schema.json"
		},
		"accessModeSufficient": {
			"$ref": "item-lists.schema.json"
		},
		"accessibilityFeature": {
			"$ref": "strings.schema.json"
		},
		"accessibilityHazard": {
			"$ref": "strings.schema.json"
		},
		"accessibilitySummary": {
			"$ref": "localizable.schema.json"
		},
		"artist": {
			"$ref": "contributor.schema.json"
		},
		"author": {
			"$ref": "contributor.schema.json"
		},
		"colorist": {
			"$ref": "contributor.schema.json"
		},
		"contributor": {
			"$ref": "contributor.schema.json"
		},
		"creator": {
			"$ref": "contributor.schema.json"
		},
		"editor": {
			"$ref": "contributor.schema.json"
		},
		"illustrator": {
			"$ref": "contributor.schema.json"
		},
		"inker": {
			"$ref": "contributor.schema.json"
		},
		"letterer": {
			"$ref": "contributor.schema.json"
		},
		"penciler": {
			"$ref": "contributor.schema.json"
		},
		"publisher": {
			"$ref": "contributor.schema.json"
		},
		"readBy": {
			"$ref": "contributor.schema.json"
		},
		"translator": {
			"$ref": "contributor.schema.json"
		},
		"url": {
			"$ref": "urls.schema.json"
		},
		"duration": {
			"$ref": "duration.schema.json"
		},
		"inLanguage": {
			"$ref": "language.schema.json"
		},
		"dateModified": {
			"$ref": "date.schema.json"
		},
		"datePublished": {
			"$ref": "date.schema.json"
		},
		"name": {
			"$ref": "localizable.schema.json"
		},
		"readingOrder": {
			"$ref": "resource.categorization.schema.json"
		},
		"resources": {
			"$ref": "resource.categorization.schema.json"
		},
		"links": {
			"$ref": "resource.categorization.schema.json"
		}
	},
	"required": [
		"@context",
		"conformsTo"
	]
}

=== marisademeglio/audiobooks-js/tests/files/manifests/manifest-resources.json
{
    "@context": [
        "https://schema.org",
        "https://www.w3.org/ns/pub-context",
        {"language" : "en", "direction": "ltr"}
    ],
    "conformsTo": "https://example.com/publication/",
    "type": "Book",
    "url": "https://publisher.example.org/mobydick",
    "author": "Herman Melville",
    "dateModified": "2018-02-10T17:00:00Z",
    "id": "fakeid",
    "readingOrder": [
        "html/title.html"
    ],

    "resources": [
        "css/mobydick.css",
        {
            "type": "LinkedResource",
            "rel": "cover",
            "url": "images/cover.jpg",
            "encodingFormat": "image/jpeg"
        },{
            "type": "LinkedResource",
            "url": "html/toc.html",
            "rel": "contents"
        },{
            "type": "LinkedResource",
            "url": "image/coverTwo.jpg",
            "rel": "cover",
            "encodingFormat": "image/jpeg"
        },{
            "type": "LinkedResource",
            "url": "fonts/STIXGeneral.otf",
            "encodingFormat": "application/vnd.ms-opentype"
        },{
            "type": "LinkedResource",
            "url": "fonts/STIXGeneralBol.otf",
            "encodingFormat": "application/vnd.ms-opentype"
        },{
            "type": "LinkedResource",
            "url": "fonts/STIXGeneralBolIta.otf",
            "encodingFormat": "application/vnd.ms-opentype"
        },{
            "type": "LinkedResource",
            "url": "fonts/STIXGeneralItalic.otf",
            "encodingFormat": "application/vnd.ms-opentype"
        }
    ]
}

=== marisademeglio/audiobooks-js/tests/files/manifests/manifest-empty-arrays.json
{
    "@context": [
        "https://schema.org",
        "https://www.w3.org/ns/pub-context",
        {"language" : "en", "direction": "ltr"}
    ],
    "conformsTo": "https://example.com/publication/",
    "type": "Book",
    "url": "https://publisher.example.org/mobydick",
    "author": "Herman Melville",
    "dateModified": "2018-02-10T17:00:00Z",
    "id": "fakeid",
    "readingOrder": [
        "html/title.html"
    ],

    "resources": [
        
    ],

    "links": [
        {
            "type": "LinkedResource",
            "url": "html/supplement.html",
            "rel": [],
            "encodingFormat": "text/html"
        }
    ]
}

=== marisademeglio/audiobooks-js/tests/files/manifests/manifest-normalize.json
{
    "@context": [
        "https://schema.org",
        "https://www.w3.org/ns/pub-context",
        {"language" : "en"}
    ],
    "conformsTo": "https://example.com/publication/",
    "type": "Book",
    "url": "https://publisher.example.org/mobydick",
    "author": "Herman Melville",
    "dateModified": "2018-02-10T17:00:00Z",
    "accessMode": "text",
    "accessibilitySummary": "This is a test",
    "readingOrder": "html/title.html",

    "resources": [
        "css/mobydick.css",
        {
            "type": "LinkedResource",
            "rel": "cover",
            "url": "images/cover.jpg",
            "encodingFormat": "image/jpeg"
        },{
            "type": "LinkedResource",
            "url": "html/toc.html",
            "rel": "contents"
        },{
            "type": "LinkedResource",
            "url": "fonts/STIXGeneral.otf",
            "encodingFormat": "application/vnd.ms-opentype"
        },{
            "type": "LinkedResource",
            "url": "fonts/STIXGeneralBol.otf",
            "encodingFormat": "application/vnd.ms-opentype"
        },{
            "type": "LinkedResource",
            "url": "fonts/STIXGeneralBolIta.otf",
            "encodingFormat": "application/vnd.ms-opentype"
        },{
            "type": "LinkedResource",
            "url": "fonts/STIXGeneralItalic.otf",
            "encodingFormat": "application/vnd.ms-opentype"
        }
    ]
}

=== marisademeglio/audiobooks-js/tests/files/manifests/manifest-case-insensitive-rel.json
{
    "@context": [
        "https://schema.org",
        "https://www.w3.org/ns/pub-context"
    ],
    "conformsTo": "https://example.com/publication/",
    "type": "Book",
    "url": "https://publisher.example.org/mobydick",
    "author": "Herman Melville",
    "dateModified": "2018-02-10T17:00:00Z",
    "name": "The Title",
    "readingOrder": [
        "html/title.html"
    ],

    "resources": [
        "css/mobydick.css",
        {
            "type": "LinkedResource",
            "rel": "coVER",
            "url": "images/cover.jpg",
            "encodingFormat": "image/jpeg"
        },{
            "type": "LinkedResource",
            "url": "html/toc.html",
            "rel": "conTEnts",
            "encodingFormat": "text/html"
        }
    ]
}
